services:
    - docker

before_install:
    - docker build -t container-crawler -f test/container/Dockerfile .
    - container_id=$(mktemp)
    - docker run -d -v `pwd`:/container-crawler container-crawler > "${container_id}"

script:
    - docker exec -it `cat ${container_id}` /bin/bash -c 'cd /container-crawler; flake8'
    - docker exec -it `cat ${container_id}` /bin/bash -c 'cd /container-crawler; nosetests --with-coverage --cover-erase --cover-branches --cover-package container_crawler test/unit'

after_success:
    - docker exec -e TRAVIS=1 -e TRAVIS_JOB_ID=${TRAVIS_JOB_ID} -e TRAVIS_BRANCH=${TRAVIS_BRANCH} -e TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST} -it `cat ${container_id}` /bin/bash -c 'cd /container-crawler; coveralls'
